name: "Ritter's Grid"
favicon: null
layout_spectrum: 0.79208
typography_spectrum: 0.34161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#add7ff'
    - '#bc7500'
    - '#0a1600'
    - '#feb800'
    - '#b70200'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
