name: "Ritter's Grid"
favicon: null
layout_spectrum: 0.90059
typography_spectrum: 0.22064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#add7ff'
    - '#bc7500'
    - '#0a1600'
    - '#feb800'
    - '#b70200'
  brandStrength: 0.75
  lightness: 0.8524378484580666
  saturation: 0.1875
  rhythmicContrast: 0.8971976598259062
purpose: []
