name: "Ritter's Grid"
favicon: null
layout_spectrum: 0.32234
typography_spectrum: 0.08867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#add7ff'
    - '#bc7500'
    - '#0a1600'
    - '#feb800'
    - '#b70200'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
